version: '3'

services:
  nginx:
    image: url-shortener-proxy
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
    restart: always
    container_name: proxy-container
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - backend

  postgres:
    image: postgres
    container_name: postgresql-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shortly
      POSTGRES_PASSWORD: shortly
      POSTGRES_DB: shortener
    volumes:
      - "./.docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql"

  backend:
    image: url-shortener-server
    build:
      dockerfile: ./server/Dockerfile
      context: .
    restart: always
    container_name: server-container
    env_file:
      - ./server/.env
    networks:
      - default
    depends_on:
      - mongo

networks:
  default:
    driver: bridge