version: '3'

services:
  postgres:
    image: postgres
    container_name: server-postgresql-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shortly
      POSTGRES_PASSWORD: shortly
      POSTGRES_DB: shortener
    volumes:
      - "./.docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql"