version: '3'

services:
  mongo:
    image: mongo
    restart: always
    container_name: server-mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: shortly
      MONGO_INITDB_ROOT_PASSWORD: shortly
      